FROM mambaorg/micromamba:1.1.0

# This dockerfile uses cached mounts, so to build use e.g.
# $ DOCKER_BUILDKIT=1 docker build .

WORKDIR /tmp

# Install man-db. We cannot use conda because man-db doesn't appear to be
# available in any conda repo
USER root
RUN apt update && apt install -y man-db
USER $MAMBA_USER

ADD singlem.yml /singlem.yml
RUN --mount=type=cache,target=/opt/conda/pkgs micromamba install -c conda-forge -c bioconda -c defaults -n base git -f /singlem.yml
RUN --mount=type=cache,target=/opt/conda/pkgs micromamba clean --all --yes
# This is needed to activate the environment in the dockerfile
ARG MAMBA_DOCKERFILE_ACTIVATE=1

RUN git clone https://github.com/wwood/singlem && cd singlem && git checkout vSINGLEM_VERSION

# Remove bundled singlem packages
RUN rm -rfv singlem/singlem/data singlem/.git singlem/appraise_plot.png

# Download default metapackage
RUN mkdir -p singlem/db && cd singlem/db && /tmp/singlem/bin/singlem data --output-directory .

######### UPDATE ME !!!!!!!!!! #########
ENV SINGLEM_METAPACKAGE_PATH=/tmp/singlem/db/SINGLEM_DB_BASENAME
# Checks whether the metapackage is up to date
RUN /tmp/singlem/bin/singlem data --verify

# Run some tests
RUN /tmp/singlem/bin/singlem --version
RUN /tmp/singlem/bin/singlem pipe --full-help 
# RUN cd singlem && python test/test_makedb_and_query.py

WORKDIR /data
ENTRYPOINT ["/usr/local/bin/_entrypoint.sh","/tmp/singlem/bin/singlem"]

# CMD /bin/bash
