#!/usr/bin/env python3

import yaml
import tomllib
import subprocess
import json
import os

base_dir = os.path.join(os.path.dirname(__file__), "..")

# Manual mapping of conda package names to their PyPI equivalents, for cases
# where the two names diverge (e.g. conda's `bird_tool_utils_python` ships the
# `bird_tool_utils` PyPI distribution). Keys and values are both lowercased.
CONDA_TO_PIP_NAME = {
    "bird_tool_utils_python": "bird_tool_utils",
}

# Load explicitly listed dependencies from pixi.toml
with open(os.path.join(base_dir, "pixi.lock"), "rb") as f:
    lock_data = yaml.safe_load(f)

# Load explicitly listed dependencies from pixi.toml
with open(os.path.join(base_dir, "pixi.toml"), "rb") as f:
    pixi_data = tomllib.load(f)

# Gather conda packages and versions from "pixi list --json"
result = subprocess.run(
    ["pixi", "list", "--json"],
    capture_output=True, text=True, check=True
)
# Parse the JSON output
pixi_list = json.loads(result.stdout)
# convert to name -> version
# exclude editable packages because that is this project
pixi_list = {pkg["name"].lower(): pkg["version"] for pkg in pixi_list if 'is_editable' not in pkg or pkg['is_editable'] is not True}

# Write requirements.txt via 'pip list --format json'
result = subprocess.run(
    ["pixi", "run", "pip", "list", "--format", "json"],
    capture_output=True, text=True, check=True
)
# Parse the JSON output
pip_list = json.loads(result.stdout)
# sort
pip_list = sorted(pip_list, key=lambda x: x["name"].lower())

# Explicitly declared packages in pixi.toml, grouped by whether the feature
# they live in is python-only, non-python, or mixed. `typical-python` and
# `typical-non-python` give us explicit segregation; other sections are mixed
# (e.g. `main` contains both shell tools and python libs).
PYTHON_SECTIONS = [["feature", "typical-python", "dependencies"]]
NONPYTHON_SECTIONS = [["feature", "typical-non-python", "dependencies"]]
MIXED_SECTIONS = [
    "dependencies",
    "host-dependencies",
    ["feature", "main", "dependencies"],
    ["feature", "main", "host-dependencies"],
]

def _read_section(section):
    if isinstance(section, list):
        d = pixi_data
        for subsec in section:
            d = d.get(subsec, {})
    else:
        d = pixi_data.get(section, {})
    print(f"Found {len(d)} declared packages in section {section}.")
    return {pkg.lower() for pkg in d}

python_conda = set().union(*(_read_section(s) for s in PYTHON_SECTIONS))
nonpython_conda = set().union(*(_read_section(s) for s in NONPYTHON_SECTIONS))
mixed_conda = set().union(*(_read_section(s) for s in MIXED_SECTIONS))
declared_conda = python_conda | nonpython_conda | mixed_conda

# Prepare environment.yml data
conda_deps = [
    f"{pkg}={pixi_list[pkg]}"
    for pkg in declared_conda if pkg in pixi_list
]
# sort conda_deps
conda_deps.sort()
env_data = {
    "channels": ["conda-forge", "bioconda"],
    "dependencies": conda_deps,
}

# Write environment.yml
with open(os.path.join(base_dir, 'admin', "environment.yml"), "w") as f:
    f.write("# This file was autogenerated by build_dep_defs_from_pixi.py - do not change manually.\n")
    yaml.dump(env_data, f, default_flow_style=False)

print("environment.yml written, with ", len(conda_deps), "dependencies.")

# Find the name of the current project to exclude from requirements.txt
project_name = pixi_data.get("workspace", {}).get("name", "").lower()
if not project_name:
    raise ValueError("Project name not found in pixi.toml.")

print("Excluding project name from requirements.txt:", project_name)

# Validate CONDA_TO_PIP_NAME against current state so stale entries are caught.
for conda_name in CONDA_TO_PIP_NAME:
    if conda_name not in declared_conda:
        raise ValueError(
            f"CONDA_TO_PIP_NAME has stale entry: conda package {conda_name!r} "
            f"is not declared in pixi.toml."
        )

# Every conda dep declared in `typical-python` must resolve to a pip package
# (directly or via CONDA_TO_PIP_NAME). `python` itself is the interpreter, not
# a pip dist, so it is excluded.
pip_names = {pkg["name"].lower() for pkg in pip_list}
required_pip_names = set()
for conda_name in python_conda:
    if conda_name == "python":
        continue
    pip_name = CONDA_TO_PIP_NAME.get(conda_name, conda_name)
    if pip_name not in pip_names:
        raise ValueError(
            f"Conda package {conda_name!r} (from feature.typical-python) does "
            f"not appear in `pip list` as {pip_name!r}. Either it failed to "
            f"install, or its PyPI name differs — add a CONDA_TO_PIP_NAME entry."
        )
    required_pip_names.add(pip_name)

# Pip names we'll accept into requirements.txt: the required python ones, plus
# anything from mixed sections that happens to also be a pip package (best
# effort — `main` mixes shell tools and python libs). Non-python conda deps
# are intentionally excluded.
mixed_pip_names = {CONDA_TO_PIP_NAME.get(p, p) for p in mixed_conda}
declared_pip = required_pip_names | mixed_pip_names

# Write requirements.txt
pip_count = 0
with open(os.path.join(base_dir, 'admin', "requirements.txt"), "w") as f:
    f.write("# This file was autogenerated by build_dep_defs_from_pixi.py - do not change manually.\n")
    for package in pip_list:
        # only include if the package is specified in pixi.toml
        if package["name"].lower() in declared_pip:
            # Skip the project itself
            if package["name"].lower() == project_name:
                continue
            pip_count += 1
            # Sometimes the version is set to 0.0.0 - unsure why - for these ones just set '*'
            if package["version"] == "0.0.0":
                line = f"{package['name']}\n"
            else:
                # If the version is not 0.0.0, write it as well
                line = f"{package['name']}=={package['version']}\n"
            f.write(line)
print("requirements.txt written, with ", pip_count, "dependencies.")
